#### general settings
name: RRDB_x2_DIV2K_BI_jpg
use_tb_logger: true
model: sr
distortion: sr
scale: 2
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: ../datasets/DIV2Ko/DIV2K_train_HR/
    dataroot_LQ: ../datasets/DIV2Ko//DIV2K_train_LR_bicubic_jpg/X2/

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: val_set5
    mode: LQGT
    dataroot_GT: ../datasets/val_set5/Set5
    dataroot_LQ: ../datasets/val_set5/Set5bicLRx2

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
# network_D:
#   which_model_D: #discriminator_vgg_128
#   in_nc: 3
#   nf: 64

#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/RRDB_PSNR_x4.pth
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 250000
  warmup_iter: -1  # no warm up
  T_period: [250000, 250000, 250000, 250000]
  restarts: [250000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
